jobs:
  name: download file ba
  on: push

  example1:
    name: save output
    steps:
      - shell: bash
        run: | 
          expr 1 + 1 > output.log
      - name: upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

#  example2:
#    name: download output
#    needs: example1
#    steps:
#      name: download output 2
#      uses: actions/download-artifact@3
#      with:
#        name: output-log-file